package io.github.PXWorld.map;

public enum PixelBehaviour {
    PIXEL_BEHAVIOUR_STATIC,
    PIXEL_BEHAVIOUR_FALLING,
    PIXEL_BEHAVIOUR_FLUID,
    PIXEL_BEHAVIOUR_SMOKE,
    PIXEL_BEHAVIOUR_OBJECT,
    PIXEL_BEHAVIOUR_BLOCKING
}
